### ISSUE TITLE
Fehler beim Aufruf des getContentElement Hooks

### ISSUE THREAD

**Issue by Aybee** [markusmilkereit/contao-boxes#2]
_1.15 - 1.16.2 auf Contao 3.3 - 3.5_

Im Zusammenspiel mit Rocksolid Columns gibt die Erweiterung einen Fehler aus.

> Warning: Missing argument 3 for MadeYourDay\Contao\Columns::getContentElementHook(), 
> **called** in /system/modules/boxes/**ModuleBoxes.php** on line **218** and 
> **defined** in system/modules/rocksolid-columns/src/MadeYourDay/Contao/**Columns.php** on line **42**
> 
> 0 system/modules/rocksolid-columns/src/MadeYourDay/Contao/Columns.php(42): 
> __error(2, 'Missing argumen...', '/is/htdocs/wp10...', 42, Array)
> 1 system/modules/boxes/ModuleBoxes.php(218): 
> MadeYourDay\Contao\Columns->getContentElementHook(Object(Magmell\Boxes\BoxesContentModule), '\n

https://github.com/madeyourday/contao-rocksolid-columns/blob/master/src/MadeYourDay/Contao/Columns.php#L42

Die Seite kann dadurch nicht mehr dargestellt werden.

Folgenden Block hatte ich irgendwann mal gepatcht, weiß aber nicht mehr was ich da gemacht hatte. Funktioniert allerdings.

https://github.com/markusmilkereit/contao-boxes/blob/master/ModuleBoxes.php#L211-L219

``` php
// HOOK: add custom logic
if (isset($GLOBALS['TL_HOOKS']['getContentElement']) && is_array($GLOBALS['TL_HOOKS']['getContentElement']))
{
    foreach ($GLOBALS['TL_HOOKS']['getContentElement'] as $callback)
    {
        $strBuffer = static::importStatic($callback[0])->$callback[1]($objRow, $strBuffer, $objElement);
    }
}

// Disable indexing if protected
if ($objElement->protected && !preg_match('/^\s*<!-- indexer::stop/', $strBuffer))
{
    $strBuffer = "\n<!-- indexer::stop -->". $strBuffer ."<!-- indexer::continue -->\n";
}
```

**Comment by markusmilkereit** [comment]
Hi Aybee - ich verstehe den Fehler nicht ganz, die Definition des Hooks in den Content-Boxen, in Contao selbst und die Funktion Columns::getContentElementHook() (aus MadeYourDay/Contao/Columns.php) haben alle 2 Parameter, warum ein fehlender dritter Parameter angemeckert wird erschliesst sich mir gerade nicht. Stehe ich auf dem Schlauch?

**Comment by Aybee** [comment]
Ok, ich habe mir das nochmal angesehen. Sorry, der Fehler scheint bei den Rocksolid Erweiterungen zu liegen.

Und obwohl ich von columns bereits die neueste Version hatte, wurde irgendwie noch ne alte Version geladen. Der 3. Parameter wurde von Rocksolid am 19.04.2015 entfernt.
https://github.com/madeyourday/contao-rocksolid-columns/commit/4e1126e7e236db674fe0004adb3d33fe6a7662ea

Nachdem jetzt die neueste Version von columns geladen wird ist der Fehler weg, aber der gleiche Fehler kommt jetzt beim frontend-helper.

Hier beim frontend-helper ist der 3. Parameter z.B. noch vorhanden
https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/master/src/MadeYourDay/Contao/FrontendHelper.php#L515

Ich werde das dort mal melden.

**Comment by Aybee** [comment]
Jetzt bin ich doch wieder hier, weil ich denke, dass bei der Deklaration des HOOKs der 3. Parameter gesetzt werden muss, da der bei Contao auch gesetzt ist.
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L483

Ich hatte das vor längerem hier schon mal gemeldet 
https://github.com/madeyourday/contao-rocksolid-frontend-helper/issues/6

Denn wenn jemand diesen HOOK mit 3 Parametern ausführen möchte, stolpert er über die Deklaration von columns, welche ihn mit 2 Parametern aufsetzt.

**Comment by markusmilkereit** [comment]
Ich hatte mich an die Doku gehalten, nicht an den Code: https://github.com/contao/docs/blob/master/manual/de/07-contao-anpassen/contao-hooks.md#getcontentelement - das ist der Master für die 3.5 (die ja noch nicht auf der Webseite steht). Ist aber dasselbe wie für 3.4 https://contao.org/de/manual/3.4/customizing-contao.html#getcontentelement 

Ich schaus mir im Detail mal an sobald es ein bisschen ruhiger ist, wahrscheinlich am Wochenende. Wahrscheinlich müsste man das wenn es wirklich falsch ist bei Contao melden, damit die Doku entsprechend angepasst wird.

**Comment by Aybee** [comment]
> Wahrscheinlich müsste man das wenn es wirklich falsch ist bei Contao melden, damit die Doku entsprechend angepasst wird.

Das hatte ich gestern bereits gemacht. Es gab schon ein Ticket dazu, welches allerdings closed war. Mal sehen, ob es bearbeitet wird.
https://github.com/contao/docs/pull/156#issuecomment-112976545

**Comment by Aybee** [comment]
Jetzt scheint es auch einen Fehler mit [haste] diesbezüglich zu geben https://community.contao.org/de/showthread.php?66218-Fehler-nach-Update-von-Erweiterungen

**Comment by fritzmg** [comment]
Der Fehler liegt bei der `boxes` Extension. Der `getContentElement` Hook von Contao hat folgende Signatur:
```
(\ContentModel, string, \ContentElement)
```
Siehe [Controller.php#L491](https://github.com/contao/core/blob/3.5.27/system/modules/core/library/Contao/Controller.php#L491)

Die Implementation des Hooks in `boxes` hat aber folgende Signatur:
``` 
(\ContentElement, string)
```
Siehe [ModuleBoxes.php#L217](https://github.com/markusmilkereit/contao-boxes/blob/f4a2f8c372b913068a3d2a86f00106c34d2eae93/ModuleBoxes.php#L217)

Daher kann es zu Fehlern kommen, wenn andere Extensions sich auf die tatsächliche Signatur verlassen.

**Comment by markusmilkereit** [comment]
Wir haben den Hook aktuell komplett deaktiviert, weil wir nicht mit einem Objekt ContentElement arbeiten, die seit Contao 4.4 zwingend vorgesehen ist. Die Boxes haben inzwischen weniger mit klassischem Inhalt zu tun als früher, der Hook hat daher seine Daseinsberechtigung verloren - wird so wahrscheinlich auch nicht mehr kommen. Ausser es gibt entsprechende Nachfragen :)

**Comment by Aybee** [comment]
Betrifft dies nur Situationen, in denen man diesen Hook mit eigener Programmierung benutzt hat, oder bedeutet dies, dass man jetzt im BE auf bestimmte Feature verzichten muss? Ich habe gerade ein Update von einer älteren Version für Contao 3.5 auf die neue 2.2.1 für Contao 4 gemacht und nun interessiert mich, ob dabei etwas auf der Strecke geblieben ist. Den HOOK habe ich nicht für eigene Programmierung im Einsatz.

**Comment by markusmilkereit** [comment]
Wir hatten den Hook eingebunden, weil sich die Content-Boxes lange sehr ähnlich verhalten haben wie Inhaltselemente. Daher lag es nahe den gleichen Hook zu verwenden (bzw. die Möglichkeit dazu zu bieten). Intern wird der Hook nicht verwendet - nur für Entwickler als Möglichkeit angeboten. Aktuell sind Boxes und Inhaltselemente zu weit auseinander, der Hook macht in der Form keinen Sinn mehr. In der Extension hat das keine Auswirkungen.

**Comment by Aybee** [comment]
Ah, ok. Vielen Dank.
