### ISSUE TITLE
Contao 3.5

### ISSUE THREAD

**Issue by Aybee** [markusmilkereit/contao-boxes#3]
Hallo Markus, pflegst du diese Erweiterung noch? Die hatte immer gute Dienste geleistet.

**Comment by markusmilkereit** [comment]
Nicht aktiv (genug), aber wir haben auf jeden Fall eine Version die unter 3.5 sauber läuft - Abgleich muss ich noch machen, landet dann auch wieder in der Erweiterungsverwaltung. Irgendwann in KW20 :)

**Comment by Aybee** [comment]
Ah, super, das ist doch mal ne Aussage. Vielen Dank. Dachte schon boxes wäre Vergangenheit. 👍

**Comment by Aybee** [comment]
**Vielen Dank** dafür, dass man boxes jetzt in Contao 4 installieren kann. Ich hatte da noch ne manuelle Installation, die auf einmal Fehler warf, als ich rocksolid-frondend-helper installiert hatte. Hatte dann hier nachgesehen und war überrascht, dass boxes jetzt kompatibel mit C4 ist. Habe die manuelle Installation entfernt und die neue aufgesetzt. Bis jetzt gibt es noch keine Fehler.

**Comment by markusmilkereit** [comment]
Wir sind hart hinterher um die alten Erweiterungen wieder zu aktivieren und sauber zu pflegen. Manch andere sind ja inzwischen überflüssig - die Funktioen von morelinks zum Beispiel bringt Contao 4.4 schon selbst mit :)
