### ISSUE TITLE
Contao 3.5.28 LTS - PHP 7

### ISSUE THREAD

**Issue by speedweb** [markusmilkereit/contao-boxes#4]
Die Erweiterung funktioniert mit Contao 3.5.28 ohne Probleme.
Wenn PHP 7 aktiviert wird läuft die Erweiterung nicht mehr.

Der Fehler müsste in den nachfolgenden Codezeilen aus der Datei ModuleBoxes.php liegen.
Kenne mich selber mit den Hooks leider zuwenig aus um den Fehler zu finden.

`		// HOOK: add custom logic
		if (isset($GLOBALS['TL_HOOKS']['getContentElement']) && is_array($GLOBALS['TL_HOOKS']['getContentElement']))
		{
			foreach ($GLOBALS['TL_HOOKS']['getContentElement'] as $callback)
			{
				$this->import($callback[0]);
				$strBuffer = $this->$callback[0]->$callback[1]($objElement, $strBuffer);
			}
		}
`

**Comment by markusmilkereit** [comment]
Vielen Dank für den Hinweis - schau ich mir an :)

**Comment by speedweb** [comment]
sorry vergessen zu schreiben....
Es handelt sich um die Version aus dem ER
Habe die Version von der nachfolgenden Adresse manuell installiert.
Diese funktioniert soweit ohne fehler...
https://github.com/Blioxxx/contao-boxes

besten Dank

**Comment by BugBuster1701** [comment]
mach aus
`$strBuffer = $this->$callback[0]->$callback[1]($objElement, $strBuffer);`
das
`$strBuffer = $this->{$callback[0]}->{$callback[1]}($objElement, $strBuffer);`

**Comment by speedweb** [comment]
Besten Dank für die Info....

**Comment by markusmilkereit** [comment]
In den aktualisierten Releases behoben.
